package ge.edu.freeuni.android.entertrainment.server.model;

import java.util.Random;

/**
 * Created by Nika Doghonadze
 */
public class NameGenerator {
    private static String[] nouns = {
            "spoon",
            "bottle cap",
            "thong",
            "nail clippers",
            "candle",
            "ice cube",
            "slipper",
            "thread",
            "glow stick",
            "needle",
            "stop sign",
            "blouse",
            "hanger",
            "rubber duck",
            "shovel",
            "bookmark",
            "model car",
            "tampon",
            "rubber band",
            "tire swing",
            "sharpie",
            "picture frame",
            "photo album",
            "nail filer",
            "tooth paste",
            "bath fizzers",
            "tissue box",
            "deodorant",
            "cookie jar",
            "rusty nail",
            "drill press",
            "chalk",
            "word search",
            "thermometer",
            "face wash",
            "paint brush",
            "candy wrapper",
            "shoe lace",
            "leg warmers",
            "wireless control",
            "boom box",
            "quilt",
            "stockings",
            "card",
            "tooth pick",
            "shawl",
            "speakers",
            "key chain",
            "cork",
            "helmet",
            "mouse pad",
            "zipper",
            "glasses",
            "lamp shade",
            "sketch pad",
            "gage",
            "plastic fork",
            "flag",
            "clay pot",
            "check book",
            "CD",
            "#2 pencil",
            "fake flowers",
            "sticky note",
            "hair tie",
            "credit card",
            "sun glasses",
            "seat belt",
            "buckel",
            "button",
            "canvas",
            "vase",
            "lip gloss",
            "rug",
            "gel",
            "twezzers",
            "toe ring",
            "scotch tape",
            "bow",
            "white out",
            "grid paper",
            "earser",
            "puddle",
            "cement stone",
            "sponge",
            "lace",
            "outlet",
            "frizz control",
            "sailboat",
            "screw",
            "sand paper",
            "eye liner",
            "pool stick",
            "pop can",
            "balloon",
            "spring",
            "ipod charger",
            "twister",
    };


    private static String[] adjectives = {
            "dead",
            "hairless",
            "sadistic",
            "metal",
            "wild",
            "domesticated",
            "abnormal",
            "medicated",
            "cocky",
            "massive",
            "disrespectful",
            "impressive",
            "out",
            "of",
            "control",
            "internet",
            "worthy",
            "hilarious",
            "sexy",
            "hot",
            "very",
            "tactful",
            "bearded",
            "duck-like",
            "violent",
            "slimy",
            "insanely",
            "creepy",
            "embarrassed",
            "to",
            "the",
            "bone",
            "self-centered",
            "talking",
            "naked",
            "angry",
            "shaky",
            "deep",
            "sick",
            "zippy",
            "sticky",
            "fluffy",
            "frozen",
            "unholy",
            "painfully",
            "honest",
            "filthy",
            "fighting",
            "bonkers",
            "harsh",
            "frisky",
            "greedy",
            "crawly",
            "insane",
            "hideous",
            "ungodly",
            "abusive",
            "drunken",
            "hateful",
            "idiotic",
            "twisted",
            "useless",
            "yapping",
            "magical",
            "indecent",
            "godawful",
            "arrogant",
            "confused",
            "flirting",
            "high-end",
            "insecure",
            "maniacal",
            "sickened",
            "slippery",
            "stubborn",
            "tripping",
            "vengeful",
            "sinister",
            "costumed",
            "cowardly",
            "haunting",
            "startled",
            "alcoholic",
            "demanding",
            "shivering",
            "offensive",
            "nighttime",
            "startling",
            "disgusting",
            "slap",
            "happy",
            "disturbing",
            "adulterous",
            "blathering",
            "flickering",
            "rebellious",
            "impertinent",
            "bull",
            "headed",
            "hyperactive",
            "infuriating",
            "outnumbered",
            "pea-brained",
            "territorial",
            "underhanded",
            "zombie",
            "like",
            "mischievous",
            "at-the-ready",
            "free-loading",
            "house-broken",
            "up-to-no-good",
            "cruel-hearted",
            "misunderstood",
            "narrow-minded",
            "self-absorbed",
            "bat-shit-crazy",
            "fiercely-loyal",
            "out-of-control",
            "fear-inspiring",
            "bat",
            "shitty",
            "crazy",
            "mentally",
            "impaired",
    };

    public static String generateRandomName() {
        Random random = new Random();
        String randomAdj = adjectives[random.nextInt(adjectives.length)];
        String randomNoun = nouns[random.nextInt(nouns.length)];
        return randomAdj + " " + randomNoun;
    }
}
